title: George Tsang's Data Analysis & Visualization Portfolio
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  linkedin: george-tsang-hk
  github: tsang-george

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
google_analytics: UA-NNNNNNNN-N
